src/objects/Install__c.object
<CustomObject>
    <fields>
        <fullName>Auditor_or_Contractor__c</fullName>
        <label>Auditor or Contractor</label>
        <picklist>
            <picklistValues>
                <fullName>Auditor Install</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Contractor Install</fullName>
            </picklistValues>
            <restrictedPicklist>true</restrictedPicklist>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Priority__c</fullName>
        <label>Priority</label>
        <precision>3</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Project__c</fullName>
        <label>Project</label>
        <referenceTo>Project__c</referenceTo>
        <relationshipLabel>Installs</relationshipLabel>
        <relationshipName>Installs</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>Install</label>
    <nameField>
        <label>Install Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Installs</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Project__c.object
<CustomObject>
    <fields>
        <fullName>Applicant_First_Name__c</fullName>
        <label>Applicant First Name</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Applicant_Last_Name__c</fullName>
        <label>Applicant Last Name</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Approved__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Generate Priority List</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Electric_Provider__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Electric Provider</label>
        <lookupFilter>
            <active>true</active>
            <errorMessage>Must be an electric utility provider</errorMessage>
            <filterItems>
                <field>Utility_Provider__c.Utility_Type__c</field>
                <operation>equals</operation>
                <value>Electric, Gas &amp; Electric</value>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Utility_Provider__c</referenceTo>
        <relationshipLabel>Projects (Electric Provider)</relationshipLabel>
        <relationshipName>Projects1</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Gas_Provider__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Gas Provider</label>
        <lookupFilter>
            <active>true</active>
            <errorMessage>Must be a Gas Utility Provider</errorMessage>
            <filterItems>
                <field>Utility_Provider__c.Utility_Type__c</field>
                <operation>equals</operation>
                <value>Gas, Gas &amp; Electric</value>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Utility_Provider__c</referenceTo>
        <relationshipLabel>Projects</relationshipLabel>
        <relationshipName>Projects</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Number_of_Potential_Installations__c</fullName>
        <label>Number of Potential Installations</label>
        <summaryForeignKey>Install__c.Project__c</summaryForeignKey>
        <summaryOperation>count</summaryOperation>
        <type>Summary</type>
    </fields>
    <fields>
        <fullName>Space_Heat_Source__c</fullName>
        <label>Space Heat Source</label>
        <picklist>
            <picklistValues>
                <fullName>Electric</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Gas</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Propane</fullName>
            </picklistValues>
            <restrictedPicklist>true</restrictedPicklist>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Water_Heat_Source__c</fullName>
        <label>Water Heat Source</label>
        <picklist>
            <picklistValues>
                <fullName>Electric</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Gas</fullName>
            </picklistValues>
            <restrictedPicklist>true</restrictedPicklist>
        </picklist>
        <type>Picklist</type>
    </fields>
    <label>Project</label>
    <nameField>
        <label>Project Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Projects</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Rebate__c.object
<CustomObject>
    <fields>
        <fullName>Auditor_or_Contractor__c</fullName>
        <formula>TEXT(Install__r.Auditor_or_Contractor__c)</formula>
        <label>Auditor or Contractor</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Deemed_Savings__c</fullName>
        <label>Deemed Savings</label>
        <precision>12</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Heat_Type__c</fullName>
        <label>Heat Type</label>
        <picklist>
            <picklistValues>
                <fullName>Space</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>DHW</fullName>
            </picklistValues>
            <restrictedPicklist>true</restrictedPicklist>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Install__c</fullName>
        <label>Install</label>
        <referenceTo>Install__c</referenceTo>
        <relationshipLabel>Rebates</relationshipLabel>
        <relationshipName>Rebates</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Priority__c</fullName>
        <formula>Install__r.Priority__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Priority</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Rebate_Amount__c</fullName>
        <label>Rebate Amount</label>
        <precision>8</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Rebate_Amount_per_Square_Foot__c</fullName>
        <label>Rebate Amount per Square Foot</label>
        <precision>6</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Rebate_as_a_Percent__c</fullName>
        <label>Rebate as a Percent</label>
        <precision>12</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Required_heat_Source__c</fullName>
        <label>Required Heat Source</label>
        <picklist>
            <picklistValues>
                <fullName>Electric</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Gas</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Either</fullName>
            </picklistValues>
            <restrictedPicklist>true</restrictedPicklist>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Up_to_Amount__c</fullName>
        <label>Up to Amount</label>
        <precision>6</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <label>Rebate</label>
    <nameField>
        <displayFormat>REBATE-{0000000}</displayFormat>
        <label>Rebate Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Rebates</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Utility_Rebate__c.object
<CustomObject>
    <fields>
        <fullName>Deemed_Savings__c</fullName>
        <label>Deemed Savings</label>
        <precision>12</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Heat_Type__c</fullName>
        <label>Heat Type</label>
        <picklist>
            <picklistValues>
                <fullName>Space</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>DHW</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Either</fullName>
            </picklistValues>
            <restrictedPicklist>true</restrictedPicklist>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Product_Installation__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Product Installation</label>
        <referenceTo>Product_Installation__c</referenceTo>
        <relationshipLabel>Utility Rebates</relationshipLabel>
        <relationshipName>Utility_Rebates</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Rebate_Amount__c</fullName>
        <label>Rebate Amount</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Rebate_Amount_per_Square_Foot__c</fullName>
        <label>Rebate Amount per Square Foot</label>
        <precision>6</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Rebate_as_a_Percent__c</fullName>
        <label>Rebate as a Percent</label>
        <precision>12</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Required_Heat_Source__c</fullName>
        <label>Required Heat Source</label>
        <picklist>
            <picklistValues>
                <fullName>Electric</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Gas</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Either</fullName>
            </picklistValues>
            <restrictedPicklist>true</restrictedPicklist>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Up_to_Amount__c</fullName>
        <label>Up to Amount</label>
        <precision>6</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Utility_Provider_del__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Utility Provider</label>
        <referenceTo>Utility_Provider__c</referenceTo>
        <relationshipLabel>Utility Rebates (Electric Provider)</relationshipLabel>
        <relationshipName>Utility_Rebates1_del</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Utility Rebate</label>
    <nameField>
        <label>Utility Rebate Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Utility Rebates</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/ProjectTriggerHandler.cls
public class ProjectTriggerHandler extends TriggerHandler {
    
    private Map<Id, Project__c> newProjectMap;
    private Map<Id, Project__c> oldProjectMap;
    private List<Project__c> newProjects;
    private Log logger;
    
    static Map<String, Id> recordTypeIdByName;
    
    static {
        recordTypeIdByName = new Map<String, Id>();
        List<RecordType> rtl = [SELECT ID, Name FROM RecordType WHERE SObjectType='Install__c'];
        for(RecordType rt : rtl){
            recordTypeIdByName.put(rt.Name, rt.Id);
        }
    }
    
    public ProjectTriggerHandler() {
        this.logger = new Log(ProjectTriggerHandler.class.getName());
        this.newProjectMap = (Map<Id, Project__c>) Trigger.newMap;
        this.oldProjectMap = (Map<Id, Project__c>) Trigger.oldMap;
        this.newProjects = (List<Project__c>) Trigger.new;
    }
    
    public override void afterInsert() {   
        logger.setEvent('afterInsert');  
        String errorMessage = '';
        
        for(Project__c project: newProjects){
            
            /**
*   Trigger Installation Logic if no installations are already associated with the project 
* 
*/ 
            //if(!approvalHasChanged(project))
            //    continue;
            
            //Boolean approved = project.Approved__c;
            Boolean approved = true;
            Decimal installCount = project.Number_of_Potential_Installations__c;
            
            logger.debug('Approved', approved);
            logger.debug('Installation Count', installCount);
            
            
            if(approved){
                /**
*  If existing installations detected, Error Out.
*/  
                if(installCount>0){
                    
                    errorMessage = 'Found ' + installCount + ' Installations(s). Please remove them before approving the project';
                    logger.debug('Log Error', errorMessage);
                    addError(project, errorMessage);
                    continue;
                    
                } 
                
                String electricUPId = project.Electric_Provider__c;
                String gasUPId = project.Gas_Provider__c;
                
                String spaceHeatSource = project.Space_Heat_Source__c;
                String waterHeatSource = project.Water_Heat_Source__c;
                
                Map<String, String> sourceByHeatType = new Map<String, String>();
                sourceByHeatType.put('Space', spaceHeatSource);
                sourceByHeatType.put('DHW', waterHeatSource);
                
                List<Utility_Rebate__c> utilityRebates = new List<Utility_Rebate__c>();
                
  
                utilityRebates = [SELECT Id, Utility_Provider_del__r.Name, Rebate_Amount__c, Product_Installation__c, 
                                                               Heat_Type__c, Required_Heat_Source__c , Product_Installation__r.RecordType.Name,
                                                               Product_Installation__r.Name, Rebate_Amount_per_Square_Foot__c, Deemed_Savings__c,
                                                               Rebate_as_a_Percent__c, Up_to_Amount__c 
                                                               FROM Utility_Rebate__c 
                                                               WHERE (Utility_Provider_del__c = :electricUPId
                                                                 OR Utility_Provider_del__c = :gasUPId)
                                                               ORDER BY Product_Installation__r.Name asc];                     
                    
              
                
                
                logger.debug('Matching Utility Rebates', utilityRebates.size());    
                
                /*
*   Logic for creating Installs. 
*   Get a unique set of product installs from the utility rebates
*   for each product install, create an install and associate
*   that to the project.
*/ 
                Set<Id> uniqueProductInstalls = new Set<Id>();
                
                for(Utility_Rebate__c utilityRebate: utilityRebates){
                    
                    uniqueProductInstalls.add(utilityRebate.Product_Installation__c);
                    
                }
                
                logger.debug('Matching Product Installs', uniqueProductInstalls.size());  
                
                List<Product_Installation__c> productInstalls = [SELECT Id, RecordTypeId, RecordType.Name, Auditor_or_Contractor__c, Name, Priority__c 
                                                                 FROM Product_Installation__c
                                                                 WHERE Id IN :uniqueProductInstalls];
                
                List<Install__c> installs = new List<Install__c>();
                
                Map<Id, Install__c> installByProductInstall = new Map<Id, Install__c>();
                
                for(Product_Installation__c productInstall: productInstalls){
                    
                    Install__c install = new Install__c();
                    
                    Id recordTypeId = recordTypeIdByName.get(productInstall.RecordType.Name);
                    
                    if(recordTypeId==null) continue;
                    
                    installByProductInstall.put(productInstall.Id, install);
                    
                    install.Name = productInstall.Name + ', ' +  project.Applicant_First_Name__c + ' ' + project.Applicant_Last_Name__c;
                    
                    install.Project__c = project.Id;
                    
                    install.RecordTypeId = recordTypeId;
                    
                    install.Install_Type__c = productInstall.Name;
                    
                    install.Auditor_or_Contractor__c = productInstall.Auditor_or_Contractor__c;
                    
                    install.Priority__c = productInstall.Priority__c;
                    
                    installs.add(install);
                }
                
                logger.debug('Install Count', installs.size());
                
                Savepoint undoinstalls = Database.setSavepoint();
                
                insert installs;
                
                logger.debug('Install By Product Install', installByProductInstall);
                
                logger.debug('Installation Successful. Now processing Rebates');
                
                List<Rebate__c> rebates = new List<Rebate__c>();
                
                logger.debug('Matching Utility Rebates', utilityRebates.size());  
                
                for(Utility_Rebate__c utilityRebate: utilityRebates){
                    
                    System.debug('Adding Utility Rebates::::');
                    
                    
                    try {
                        
                        logger.debug('Utility Rebate Attributes', utilityRebate);
                        Rebate__c rebate = new Rebate__c();
                        rebate.Utility_Provider__c = utilityRebate.Utility_Provider_del__c;
                        if(utilityRebate.Heat_Type__c!='Either'){
                            rebate.Heat_Type__c = utilityRebate.Heat_Type__c;
                            String heatSource = sourceByHeatType.get(utilityRebate.Heat_Type__c);
                            System.debug('Required Heat Source='+ heatSource +' For Heat Type=' + utilityRebate.Heat_Type__c);
                            System.debug('Eligible Heat Source='+ utilityRebate.Required_Heat_Source__c +' For Heat Type=' + utilityRebate.Heat_Type__c);
                            if(heatSource!=utilityRebate.Required_Heat_Source__c){
                                System.debug('Skipping the rebate');
                                continue;
                            }else{
                                System.debug('Including this rebate:'+ utilityRebate.Rebate_Amount__c);
                            }
                        }
                            
                        
                        rebate.Required_heat_Source__c = utilityRebate.Required_Heat_Source__c;
                        rebate.Up_to_Amount__c = utilityRebate.Up_to_Amount__c;
                        rebate.Deemed_Savings__c = utilityRebate.Deemed_Savings__c;
                        rebate.Rebate_as_a_Percent__c = utilityRebate.Rebate_as_a_Percent__c;
                        
                        rebate.Rebate_Amount__c = utilityRebate.Rebate_Amount__c;
                        rebate.Rebate_Amount_per_Square_Foot__c = utilityRebate.Rebate_Amount_per_Square_Foot__c;
                        rebate.Install__c = getRebateId(utilityRebate, installByProductInstall);
                        rebate.Eligible_Rebate__c = true;
                        rebates.add(rebate);                        
                    } catch(Exception e) {
                        logger.debug('Error While Creating Rebates', e.getMessage());
                    }
                    
                    
                }                
                
                logger.debug('Rebate Count', rebates.size());
                
                try 
                {
                    
                    insert rebates;
                    
                }
                catch(Exception e)
                {   
                    errorMessage = ' While creating rebates, encountered this issue =>' + e.getMessage().substring(e.getMessage().indexOf(':')) + '<br/>Contact your admin.<br/>';
                    Database.rollback(undoinstalls);
                    logger.debug('Installs Rolled back successfully');
                    logger.debug('Log Error', errorMessage);
                    addError(project, errorMessage);
                    continue;                    
                    
                }
                
            }
        }
    } 
    
    public override void beforeUpdate() {
        logger.setEvent('before Update');
    }
    
    
    private void addError(SObject p, String error){
        newProjectMap.get(p.Id).addError(error, false);
    }
    
    private Boolean approvalHasChanged(Project__c p){
        return(oldProjectMap.get(p.Id).Approved__c!=p.Approved__c);
    }
    
    private Id getRebateId(Utility_Rebate__c ur, Map<Id, Install__c> installByProductInstall){
        Install__c ins =  installByProductInstall.get(ur.Product_Installation__c);
        if(ins==null){
            logger.debug('Install missing', ur.Product_Installation__c);
        }
        return ins.Id;
    }
    
}