src/objects/Install__c.object
<CustomObject>
    <fields>
        <fullName>Auditor_or_Contractor__c</fullName>
        <label>Auditor or Contractor</label>
        <picklist>
            <picklistValues>
                <fullName>Auditor Install</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Contractor Install</fullName>
            </picklistValues>
            <restrictedPicklist>true</restrictedPicklist>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Project__c</fullName>
        <label>Project</label>
        <referenceTo>Project__c</referenceTo>
        <relationshipLabel>Installs</relationshipLabel>
        <relationshipName>Installs</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>Install</label>
    <nameField>
        <label>Install Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Installs</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Project__c.object
<CustomObject>
    <fields>
        <fullName>Applicant_First_Name__c</fullName>
        <label>Applicant First Name</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Applicant_Last_Name__c</fullName>
        <label>Applicant Last Name</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Approved__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Generate Priority List</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Electric_Utility_Provider__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Electric Utility Provider</label>
        <referenceTo>Utility_Provider__c</referenceTo>
        <relationshipLabel>Projects (Electric Utility Provider)</relationshipLabel>
        <relationshipName>Projects2</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Gas_Provider__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Gas Provider</label>
        <lookupFilter>
            <active>true</active>
            <errorMessage>Must be a Gas Utility Provider</errorMessage>
            <filterItems>
                <field>Utility_Provider__c.Utility_Type__c</field>
                <operation>equals</operation>
                <value>Gas, Gas &amp; Electric</value>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Utility_Provider__c</referenceTo>
        <relationshipLabel>Projects</relationshipLabel>
        <relationshipName>Projects</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Project</label>
    <nameField>
        <label>Project Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Projects</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Utility_Provider__c.object
<CustomObject>
    <fields>
        <fullName>Utility_Type__c</fullName>
        <label>Utility Type</label>
        <picklist>
            <picklistValues>
                <fullName>Electric</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Gas</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Gas &amp; Electric</fullName>
            </picklistValues>
            <restrictedPicklist>true</restrictedPicklist>
        </picklist>
        <type>Picklist</type>
    </fields>
    <label>Utility Provider</label>
    <nameField>
        <label>Utility Provider Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Utility Providers</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Utility_Rebate__c.object
<CustomObject>
    <fields>
        <fullName>Product_Installation__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Product Installation</label>
        <referenceTo>Product_Installation__c</referenceTo>
        <relationshipLabel>Utility Rebates</relationshipLabel>
        <relationshipName>Utility_Rebates</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Utility_Provider_del__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Utility Provider</label>
        <referenceTo>Utility_Provider__c</referenceTo>
        <relationshipLabel>Utility Rebates (Electric Provider)</relationshipLabel>
        <relationshipName>Utility_Rebates1_del</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Utility Rebate</label>
    <nameField>
        <label>Utility Rebate Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Utility Rebates</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/ProjectTriggerTest.cls
@istest
public class ProjectTriggerTest 
{
	public static testmethod void projectTriggerTestmethod()
    {
        try
        {
            Product_Installation__c productInsta=new Product_Installation__c();
            productInsta.Name='Air Sealing';
            productInsta.Auditor_or_Contractor__c='Auditor Install';
            insert productInsta;
            
            Utility_Provider__c utilProvElec=new Utility_Provider__c();
            utilProvElec.Name='test util elec provider';
            utilProvElec.Utility_Type__c='Electric';
            insert utilProvElec;
            
            Utility_Provider__c utilProvGas=new Utility_Provider__c();
            utilProvGas.Name='test util gas provider';
            utilProvGas.Utility_Type__c='Gas';
            insert utilProvGas;
            
            Utility_Rebate__c utilReb=new Utility_Rebate__c();
            utilReb.Product_Installation__c=productInsta.Id;
            utilReb.Utility_Provider_del__c=utilProvGas.id;
            insert utilReb;
            
            Project__c projObj= new Project__c();
            projObj.Electric_Utility_Provider__c=utilProvElec.Id;
            projObj.Gas_Provider__c=utilProvGas.Id;
            
            insert projObj;
            
            projObj.Approved__c=True;
            update projObj;
            
        }
        catch(exception ex)
        {
            system.debug('ex msg ' + ex.getMessage());
            system.debug('ex line ' + ex.getLineNumber());
        }
    }
    
	public static testmethod void projectWithInstallTriggerTestmethod()
    {
        try
        {
            Product_Installation__c productInsta=new Product_Installation__c();
            productInsta.Name='Air Sealing';
            productInsta.Auditor_or_Contractor__c='Auditor Install';
            insert productInsta;
            
  
            
            Utility_Provider__c utilProvElec=new Utility_Provider__c();
            utilProvElec.Name='test util elec provider';
            utilProvElec.Utility_Type__c='Electric';
            insert utilProvElec;
            
            Utility_Provider__c utilProvGas=new Utility_Provider__c();
            utilProvGas.Name='test util gas provider';
            utilProvGas.Utility_Type__c='Gas';
            insert utilProvGas;
            
            Utility_Rebate__c utilReb=new Utility_Rebate__c();
            utilReb.Product_Installation__c=productInsta.Id;
            utilReb.Utility_Provider_del__c=utilProvGas.id;
            insert utilReb;
            
            Project__c projObj= new Project__c();
            projObj.Electric_Utility_Provider__c=utilProvElec.Id;
            projObj.Gas_Provider__c=utilProvGas.Id;
            projObj.Applicant_First_Name__c ='FN';
            projObj.Applicant_Last_Name__c = 'LN';
            
            insert projObj;
            
            Install__c install=new Install__c();
            install.Project__c = projObj.Id;
            install.Auditor_or_Contractor__c='Auditor Install';
            
            insert install;
            
            Install__c inst = [SELECT Name FROM Install__c WHERE Project__c = :projObj.Id LIMIT 1];
            System.assert(inst.Name<>'');
            
            projObj.Approved__c=True;
            update projObj;
            
        }
        catch(exception ex)
        {
            system.debug('ex msg ' + ex.getMessage());
            system.debug('ex line ' + ex.getLineNumber());
        }
    }    
}